# PCA

In [119]:
import numpy as np

In [134]:
A = np.array([[3,0],[4,5]])

In [135]:
cov, vectors = np.linalg.eig((A.T @ A))

In [136]:
values, V = np.linalg.eig((A.T @ A))

In [137]:
values, U = np.linalg.eig((A @ A.T))

In [138]:
U 

array([[-0.9486833 , -0.31622777],
       [ 0.31622777, -0.9486833 ]])

In [139]:
V

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [140]:
cov

array([45.,  5.])

In [141]:
(U @ np.diag(np.sqrt(cov)) @ V.T)

array([[-4.00000000e+00, -5.00000000e+00],
       [ 3.00000000e+00, -6.66133815e-16]])

In [142]:
np.diag(np.sqrt(cov))

array([[6.70820393, 0.        ],
       [0.        , 2.23606798]])

In [143]:
U * np.sqrt(10)

array([[-3., -1.],
       [ 1., -3.]])

In [144]:
V * np.sqrt(2)

array([[ 1., -1.],
       [ 1.,  1.]])

In [149]:
U1 = np.reshape(np.concatenate((U[1,:], -U[0,:]), axis=0), (2,2))
U1 * np.sqrt(10)

array([[ 1., -3.],
       [ 3.,  1.]])

In [153]:
U1 @ np.diag(np.sqrt(cov)) @ V.T

array([[ 3.00000000e+00, -6.66133815e-16],
       [ 4.00000000e+00,  5.00000000e+00]])